/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import java.util.Date;
import todoApp.controller.ProjectController;
import todoApp.controller.TaskController;
import todoApp.model.Project;
import todoApp.model.Task;

public class App {

    public static void main(String[] args) {

        TaskController taskController = new TaskController();

        Task task = taskController.get(5);

        System.out.println(task);

        task.setIsCompleted(true);

        System.out.println(task);

        taskController.update(task);

    }

}
