/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import com.mysql.jdbc.Connection;
import java.util.Date;
import todoApp.util.ConnectionFactory;

public class App {

    public static void main(String[] args) {
        Date today;
        long miliseconds = 1500;
        today = new Date(miliseconds);
        java.sql.Date sqlToday;
        sqlToday = new java.sql.Date(today.getTime());
        System.out.println(today);
        System.out.println(sqlToday);
    }
}
